### ISSUE TITLE
Write a C++ code to do Nested list in C++ STL <Open Ended>

### ISSUE THREAD

**Issue by saurabhGr** [saurabhGr/Programming-Data-Structure-using-C#20]
[list in STL] is used to represent a linked list in C++. How to create a nested list. We are given n lists, we need to create a list of n lists. Examples:

Input :  Number of lists: 2
1st list: {1 2}
2nd list:  {3 4 5 6}
Output : 
[
  [ 1  2 ]
  [ 3  4  5  6 ]
]

Input : Number of lists: 3
1st list : {0 1} 
2nd list : {1 2 3}
3rd list : {2 3 4 5}
Output :
[
  [ 0  1 ]
  [ 1  2  3 ]
  [ 2  3  4  5 ]
]

**Comment by Patelg5606** [comment]
Hey, I would like to contribute this code, Please assign it to me.

**Comment by dikshant182004** [comment]
hii @plz assign this issue to me.
