### ISSUE TITLE
Write a C++ Program to do Constructor in Multiple Inheritance <Open Ended>

### ISSUE THREAD

**Issue by saurabhGr** [saurabhGr/Programming-Data-Structure-using-C#21]
Constructor is a class member function with the same name as the class. The main job of the constructor is to allocate memory for class objects. Constructor is automatically called when the object is created. 

Multiple Inheritance:

Multiple Inheritance is a feature of C++ where a class can derive from several(two or more) base classes. The constructors of inherited classes are called in the same order in which they are inherited.

**Comment by dikshant182004** [comment]
hii @saurabhGr plz assign this issue to me
