### ISSUE TITLE
Write a C++ code to do Function Overloading and Return Type in C++ <Open Ended>

### ISSUE THREAD

**Issue by saurabhGr** [saurabhGr/Programming-Data-Structure-using-C#23]
Function overloading is possible in C++ and Java but only if the functions must differ from each other by the types and the number of arguments in the argument list. However, functions can not be overloaded if they differ only in the return type. 

Why is Function overloading not possible with different return types? 

Function overloading comes under the compile-time polymorphism. During compilation, the function signature is checked. So, functions can be overloaded, if the signatures are not the same. The return type of a function has no effect on function overloading, therefore the same function signature with different return type will not be overloaded. 

Example: if there are two functions: int sum() and float sum(), these two will generate a compile-time error as function overloading is not possible here.

**Comment by dikshant182004** [comment]
hii @saurabhGr plz assign this issue to me as it seems a perfect fit for my open source contribution
